#!/usr/bin/env bash
# After install-infra has installed the AAP operator, create a standalone
# AnsibleAutomationPlatform in a non-OSAC namespace, mint an API token, and
# write a Helm overlay that points make install-osac at that controller.
#
# Required env:
#   KUBECONFIG
#   OSAC_NAMESPACE
#   OVERLAY_PATH          file to write (consumed as INSTANCE_VALUES_EXTRA -f)
#
# Optional env:
#   AAP_NAMESPACE         default aap-acm
#   AAP_NAME              default external-aap
#   TOKEN_SECRET_NAME     default my-aap-token
#   AAP_WAIT_SECONDS      default 2400
set -euo pipefail

: "${KUBECONFIG:?KUBECONFIG is required}"
: "${OSAC_NAMESPACE:?OSAC_NAMESPACE is required}"
: "${OVERLAY_PATH:?OVERLAY_PATH is required}"

AAP_NAMESPACE="${AAP_NAMESPACE:-aap-acm}"
AAP_NAME="${AAP_NAME:-external-aap}"
TOKEN_SECRET_NAME="${TOKEN_SECRET_NAME:-my-aap-token}"
AAP_WAIT_SECONDS="${AAP_WAIT_SECONDS:-2400}"
TOKEN_KEY="${TOKEN_KEY:-token}"

command -v oc >/dev/null 2>&1 || {
  echo "provision-external-aap: oc is required" >&2
  exit 1
}
command -v python3 >/dev/null 2>&1 || {
  echo "provision-external-aap: python3 is required" >&2
  exit 1
}

log() {
  echo "$*" >&2
}

poll_until() {
  local description=$1
  local deadline=$((SECONDS + AAP_WAIT_SECONDS))
  shift
  while ((SECONDS < deadline)); do
    if "$@" >/dev/null 2>&1; then
      log "${description}: ready"
      return 0
    fi
    log "${description}: not ready, retrying in 15s..."
    sleep 15
  done
  log "ERROR: timed out waiting for ${description} after ${AAP_WAIT_SECONDS}s"
  return 1
}

log "Waiting for AnsibleAutomationPlatform CRD (AAP operator)..."
poll_until "CRD ansibleautomationplatforms.aap.ansible.com" \
  oc get crd ansibleautomationplatforms.aap.ansible.com

oc create namespace "${AAP_NAMESPACE}" --dry-run=client -o yaml | oc apply -f -
log "Installing standalone AnsibleAutomationPlatform/${AAP_NAME} in ${AAP_NAMESPACE}"
oc apply -f - <<EOF
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: ${AAP_NAME}
  namespace: ${AAP_NAMESPACE}
spec:
  controller:
    disabled: false
  eda:
    disabled: true
  hub:
    disabled: true
  lightspeed:
    disabled: true
  image_pull_policy: IfNotPresent
  no_log: true
  redis_mode: standalone
  route_tls_termination_mechanism: Edge
EOF

ADMIN_SECRET="${AAP_NAME}-admin-password"
poll_until "secret/${ADMIN_SECRET}" \
  oc get secret "${ADMIN_SECRET}" -n "${AAP_NAMESPACE}"

poll_until "route/${AAP_NAME} host" \
  bash -c "[[ -n \"\$(oc get route \"${AAP_NAME}\" -n \"${AAP_NAMESPACE}\" -o jsonpath='{.spec.host}' 2>/dev/null)\" ]]"

ROUTE_HOST=$(oc get route "${AAP_NAME}" -n "${AAP_NAMESPACE}" -o jsonpath='{.spec.host}')
AAP_URL="https://${ROUTE_HOST}/api/controller"
log "External AAP route: https://${ROUTE_HOST}"
log "Will pass AAP URL ${AAP_URL} to the OSAC installer"

AAP_PASSWORD=$(oc get secret "${ADMIN_SECRET}" -n "${AAP_NAMESPACE}" -o jsonpath='{.data.password}' | base64 -d)
NETRC=$(mktemp)
BODY=$(mktemp)
trap 'rm -f "${NETRC}" "${BODY}"' EXIT
umask 077
printf 'machine %s\nlogin admin\npassword %s\n' "${ROUTE_HOST}" "${AAP_PASSWORD}" >"${NETRC}"
unset AAP_PASSWORD

# Sets MINT_HTTP_CODE and writes the response body to $BODY.
mint_token() {
  local path=$1
  : >"${BODY}"
  MINT_HTTP_CODE=$(curl -sk --connect-timeout 5 --max-time 30 \
    --netrc-file "${NETRC}" \
    -H "Content-Type: application/json" \
    -X POST \
    -d '{"description": "osac-e2e-external-aap", "scope": "write"}' \
    -o "${BODY}" -w '%{http_code}' \
    "https://${ROUTE_HOST}${path}" || true)
}

token_from_json() {
  python3 -c 'import json,sys; data=json.load(sys.stdin); token=data.get("token") or ""; print(token)'
}

TOKEN=""
deadline=$((SECONDS + AAP_WAIT_SECONDS))
while ((SECONDS < deadline)); do
  for path in /api/gateway/v1/tokens/ /api/controller/v2/tokens/; do
    mint_token "${path}"
    case "${MINT_HTTP_CODE}" in
      401 | 403)
        log "ERROR: AAP token API ${path} returned HTTP ${MINT_HTTP_CODE}; not retrying"
        exit 1
        ;;
    esac
    TOKEN=$(token_from_json <"${BODY}" 2>/dev/null || true)
    if [[ -n "${TOKEN}" ]]; then
      log "Minted AAP API token via ${path}"
      break 2
    fi
  done
  log "AAP token API not ready (last HTTP ${MINT_HTTP_CODE:-none}), retrying in 20s..."
  sleep 20
done
[[ -n "${TOKEN}" ]] || {
  log "ERROR: could not mint an AAP API token from https://${ROUTE_HOST}"
  exit 1
}
if [[ -n "${GITHUB_ACTIONS:-}" ]]; then
  echo "::add-mask::${TOKEN}"
fi

oc create namespace "${OSAC_NAMESPACE}" --dry-run=client -o yaml | oc apply -f -
oc create secret generic "${TOKEN_SECRET_NAME}" \
  --from-literal="${TOKEN_KEY}=${TOKEN}" \
  -n "${OSAC_NAMESPACE}" \
  --dry-run=client -o yaml | oc apply -f -
unset TOKEN

cat >"${OVERLAY_PATH}" <<EOF
# Generated by provision-external-aap.sh for OSAC-5228 complementary e2e.
# publishTemplates is off: this AAP is a fresh controller without OSAC
# job templates. Helm --wait would fail the publish-templates hook otherwise.
global:
  externalAap: &externalAap
    enabled: true
    url: "${AAP_URL}"
    tokenSecret:
      name: "${TOKEN_SECRET_NAME}"
      key: "${TOKEN_KEY}"
aap:
  externalAap: *externalAap
  aap:
    instance:
      enabled: false
  bootstrap:
    enabled: false
  apiToken:
    create: false
  instanceGroups:
    publishTemplates:
      enabled: false
EOF

log "Wrote installer overlay ${OVERLAY_PATH}"
if [[ -n "${GITHUB_ENV:-}" ]]; then
  {
    echo "EXTERNAL_AAP_URL=${AAP_URL}"
    echo "EXTERNAL_AAP_OVERLAY=${OVERLAY_PATH}"
    echo "EXTERNAL_AAP_TOKEN_SECRET=${TOKEN_SECRET_NAME}"
    echo "EXTERNAL_AAP_NAMESPACE=${AAP_NAMESPACE}"
    echo "EXTERNAL_AAP_NAME=${AAP_NAME}"
  } >>"${GITHUB_ENV}"
fi
echo "${AAP_URL}"
