---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart socat forwarders
  shell: |
    systemctl daemon-reload
    for svc in $(systemctl list-units --type=service --all | grep socat-forwarder | awk '{print $1}'); do
      systemctl restart "$svc"
    done
  changed_when: true
