apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: cert-manager
  name: cert-manager
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart: https://charts.jetstack.io/charts/cert-manager-v1.7.3.tgz
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
